/* Auto-generated by genmsg_cpp for file /home/armuser/ros/pose_msgs/msg/Transforms.msg */
#ifndef POSE_MSGS_MESSAGE_TRANSFORMS_H
#define POSE_MSGS_MESSAGE_TRANSFORMS_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "std_msgs/Header.h"
#include "pose_msgs/Transform.h"

namespace pose_msgs
{
template <class ContainerAllocator>
struct Transforms_ {
  typedef Transforms_<ContainerAllocator> Type;

  Transforms_()
  : header()
  , transforms()
  {
  }

  Transforms_(const ContainerAllocator& _alloc)
  : header(_alloc)
  , transforms(_alloc)
  {
  }

  typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
   ::std_msgs::Header_<ContainerAllocator>  header;

  typedef std::vector< ::pose_msgs::Transform_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::pose_msgs::Transform_<ContainerAllocator> >::other >  _transforms_type;
  std::vector< ::pose_msgs::Transform_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::pose_msgs::Transform_<ContainerAllocator> >::other >  transforms;


  ROS_DEPRECATED uint32_t get_transforms_size() const { return (uint32_t)transforms.size(); }
  ROS_DEPRECATED void set_transforms_size(uint32_t size) { transforms.resize((size_t)size); }
  ROS_DEPRECATED void get_transforms_vec(std::vector< ::pose_msgs::Transform_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::pose_msgs::Transform_<ContainerAllocator> >::other > & vec) const { vec = this->transforms; }
  ROS_DEPRECATED void set_transforms_vec(const std::vector< ::pose_msgs::Transform_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::pose_msgs::Transform_<ContainerAllocator> >::other > & vec) { this->transforms = vec; }
private:
  static const char* __s_getDataType_() { return "pose_msgs/Transforms"; }
public:
  ROS_DEPRECATED static const std::string __s_getDataType() { return __s_getDataType_(); }

  ROS_DEPRECATED const std::string __getDataType() const { return __s_getDataType_(); }

private:
  static const char* __s_getMD5Sum_() { return "b05261b83f610815089214ecd5899234"; }
public:
  ROS_DEPRECATED static const std::string __s_getMD5Sum() { return __s_getMD5Sum_(); }

  ROS_DEPRECATED const std::string __getMD5Sum() const { return __s_getMD5Sum_(); }

private:
  static const char* __s_getMessageDefinition_() { return "# This represents a transormation message\n\
Header header\n\
pose_msgs/Transform[] transforms\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.secs: seconds (stamp_secs) since epoch\n\
# * stamp.nsecs: nanoseconds since stamp_secs\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: pose_msgs/Transform\n\
# This represents a transormation message\n\
\n\
time time\n\
string frameSrc\n\
string frameDes\n\
geometry_msgs/Vector3 translation\n\
geometry_msgs/Vector3 rotation\n\
================================================================================\n\
MSG: geometry_msgs/Vector3\n\
# This represents a vector in free space. \n\
\n\
float64 x\n\
float64 y\n\
float64 z\n\
"; }
public:
  ROS_DEPRECATED static const std::string __s_getMessageDefinition() { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED const std::string __getMessageDefinition() const { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED virtual uint8_t *serialize(uint8_t *write_ptr, uint32_t seq) const
  {
    ros::serialization::OStream stream(write_ptr, 1000000000);
    ros::serialization::serialize(stream, header);
    ros::serialization::serialize(stream, transforms);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint8_t *deserialize(uint8_t *read_ptr)
  {
    ros::serialization::IStream stream(read_ptr, 1000000000);
    ros::serialization::deserialize(stream, header);
    ros::serialization::deserialize(stream, transforms);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint32_t serializationLength() const
  {
    uint32_t size = 0;
    size += ros::serialization::serializationLength(header);
    size += ros::serialization::serializationLength(transforms);
    return size;
  }

  typedef boost::shared_ptr< ::pose_msgs::Transforms_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::pose_msgs::Transforms_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct Transforms
typedef  ::pose_msgs::Transforms_<std::allocator<void> > Transforms;

typedef boost::shared_ptr< ::pose_msgs::Transforms> TransformsPtr;
typedef boost::shared_ptr< ::pose_msgs::Transforms const> TransformsConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::pose_msgs::Transforms_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::pose_msgs::Transforms_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace pose_msgs

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::pose_msgs::Transforms_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::pose_msgs::Transforms_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::pose_msgs::Transforms_<ContainerAllocator> > {
  static const char* value() 
  {
    return "b05261b83f610815089214ecd5899234";
  }

  static const char* value(const  ::pose_msgs::Transforms_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xb05261b83f610815ULL;
  static const uint64_t static_value2 = 0x089214ecd5899234ULL;
};

template<class ContainerAllocator>
struct DataType< ::pose_msgs::Transforms_<ContainerAllocator> > {
  static const char* value() 
  {
    return "pose_msgs/Transforms";
  }

  static const char* value(const  ::pose_msgs::Transforms_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::pose_msgs::Transforms_<ContainerAllocator> > {
  static const char* value() 
  {
    return "# This represents a transormation message\n\
Header header\n\
pose_msgs/Transform[] transforms\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.secs: seconds (stamp_secs) since epoch\n\
# * stamp.nsecs: nanoseconds since stamp_secs\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: pose_msgs/Transform\n\
# This represents a transormation message\n\
\n\
time time\n\
string frameSrc\n\
string frameDes\n\
geometry_msgs/Vector3 translation\n\
geometry_msgs/Vector3 rotation\n\
================================================================================\n\
MSG: geometry_msgs/Vector3\n\
# This represents a vector in free space. \n\
\n\
float64 x\n\
float64 y\n\
float64 z\n\
";
  }

  static const char* value(const  ::pose_msgs::Transforms_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct HasHeader< ::pose_msgs::Transforms_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct HasHeader< const ::pose_msgs::Transforms_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::pose_msgs::Transforms_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.header);
    stream.next(m.transforms);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct Transforms_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::pose_msgs::Transforms_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::pose_msgs::Transforms_<ContainerAllocator> & v) 
  {
    s << indent << "header: ";
s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "transforms[]" << std::endl;
    for (size_t i = 0; i < v.transforms.size(); ++i)
    {
      s << indent << "  transforms[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::pose_msgs::Transform_<ContainerAllocator> >::stream(s, indent + "    ", v.transforms[i]);
    }
  }
};


} // namespace message_operations
} // namespace ros

#endif // POSE_MSGS_MESSAGE_TRANSFORMS_H

